# -*- coding: utf-8 -*-
"""Scene plan — "하이에나와 사자" (잘해줄수록 을이 되는 이유).

(start_line, kind, kwargs). A scene runs until the next one starts; every
timed element inside names the line it lands on. `nocap` drops the bottom
caption where the same words are already the picture (chat bubbles, quotes).
Line numbers index script.txt (0-based).
"""

SCENES = [
    # ── HOOK: the unanswered phone, nothing laid over it ─────────────────────
    (0, "hook", dict(key="v_phone")),
    (4, "photo", dict(key="br_cafe_two", kb="in")),
    (5, "typo", dict(parts=[(5, "그런데, 이상한 일이 생긴다", "")], nocap=[5])),
    (6, "graph_reverse", dict(a_at=7, b_at=8, lab_a="내 호감", lab_b="상대 답장 속도",
                              note=(9, "나는 기다리는 쪽"))),
    (10, "chat", dict(title="썸녀", msgs=[(11, "me", "언제가 편하세요?"),
                                         (12, "me", "어디 가고 싶으세요?"),
                                         (13, "me", "저는 아무거나 괜찮아요.")],
                      typing_at=14, nocap=[11, 12, 13])),
    (15, "distance", dict(reach_at=16, back_at=17)),
    (18, "quotes", dict(bgkey="p_bed", side="R", quotes=[(20, "여자는 나쁜 남자를 좋아하나?", "th"),
                                                        (21, "내 외모가 부족한 건가?", "th")],
                        layout="zig", nocap=[20, 21])),
    (22, "typo", dict(parts=[(22, "그 해석은", "dim"), (23, "문제의 절반만 본다", "hl")])),
    (24, "rows", dict(items=[(24, "착한 게 문제", "no"), (25, "잘해주는 게 문제", "no"),
                             (26, "잘해줄 수 있어야 한다", "ok")])),
    (27, "typo", dict(parts=[(27, "진짜 문제는", "am"), (28, "잘해주면서", "dim"),
                             (29, "어디에 서게 되느냐", "am")])),
    (30, "quotes", dict(cut="cut_man_anx_1", quotes=[(32, "“나는 이 사람에게\n선택받아야 하는 사람이다.”", "y")],
                        nocap=[32])),
    (34, "scale", dict(title="관계의 갑과 을", steps=[(34, -10)], left="갑", right="을")),
    (36, "rows", dict(title="흔히 생각하는 갑과 을",
                      items=[(36, "누가 먼저 연락하느냐", "n"), (37, "누가 답장을 늦게 하느냐", "n"),
                             (38, "누가 더 좋아하느냐", "n")])),
    (40, "typo", dict(parts=[(41, "갑과 을을 가르는 것", "am"), (42, "누가 더 좋아하느냐", "dim x"),
                             (43, "누가 먼저 자기 기준을 포기하느냐", "am hl")], nocap=[43])),

    # ── CH1 선택권 ───────────────────────────────────────────────────────────
    (45, "chapter", dict(num="01", title="선택권을 넘기는 순간", key="br_silence_table")),
    (46, "photo", dict(key="p_food", kb="out", tags=[(46, "파스타", "left:300px;top:200px", ""),
                                                     (46, "고기 ♥", "right:320px;top:200px", "am")])),
    (47, "video", dict(key="v_date", side="R", nocap=[48, 50, 52],
                       quotes=[(48, "뭐 드시고 싶으세요?", "y", "나"), (50, "저는 아무거나 괜찮아요.", "", "그녀"),
                               (52, "진짜 먹고 싶은 거 없어요?", "y", "나")])),
    (53, "typo", dict(parts=[(53, "왜 이럴까?", ""), (54, "본인은 ‘배려’라고 생각한다", "am")], nocap=[53, 54])),
    (55, "quotes", dict(cut="cut_man_anx_2", quotes=[(57, "내가 고른 곳을 싫어하면?", "th"),
                                                    (58, "마음대로 하는 사람처럼 보이면?", "th"),
                                                    (59, "괜히 감점되면?", "th")], layout="zig",
                        nocap=[57, 58, 59])),
    (60, "iceberg", dict(top="배려심 있는 남자", bottom="거절이 두려워 기준을 숨김",
                         top_at=61, bot_at=62)),
    (65, "tokens", dict(items=[(67, "다음 장소"), (68, "만나는 시간"), (69, "카톡 속도"),
                               (70, "대화 주제"), (71, "호감 표현")])),
    (73, "scale", dict(steps=[(73, -4), (75, -9), (76, -13, .1), (76, -17, 1.0)], left="상대", right="나",
                       drops=[(75, "선택권"), (76, "선택권", .05), (76, "선택권", .95)])),
    (77, "quotes", dict(quotes=[(79, "내가 다 정해야 하나?", "dk"), (80, "잘해주면 안 되나?", "dk"),
                                (81, "연락도 일부러 늦게?", "dk"), (82, "나쁜 남자처럼?", "dk")],
                        nocap=[79, 80, 81, 82])),
    (83, "typo", dict(parts=[(83, "아닙니다", "")], nocap=[83])),
    (84, "pull", dict(label_at=85, a_at=86, b_at=87)),
    (88, "rows", dict(title="본질은 그대로", items=[(89, "여전히 상대 반응에 집착", "q"),
                                                (90, "여전히 관계를 힘겨루기로 본다", "q")])),

    # ── 중심 ────────────────────────────────────────────────────────────────
    (91, "core", dict(steps=[(91, "중심 있는 태도", "cy"), (92, "상대를 누르는 게 아니다", "")])),
    (93, "typo", dict(parts=[(93, "반응과 관계없이", "dim"), (94, "내 기준을 유지하는 상태", "cy")], nocap=[94])),
    (95, "quotes", dict(bgkey="p_calm", side="R", dim=.5, quotes=[(95, "나는 이 음식이 좋고", "cy"),
                                                                   (96, "이런 데이트를 좋아하고", "cy"),
                                                                   (97, "당신에게 호감이 있고", "cy"),
                                                                   (98, "이런 관계를 원한다", "cy")])),
    (100, "eq", dict(rows=[(100, "상대의 거절", "내 가치 없음"), (102, "상대 존중", "나를 바꾸기")])),
    (105, "typo", dict(parts=[(105, "반응 하나에 다른 사람이 되지 않는 것", "am")])),

    # ── 코칭 현장 ────────────────────────────────────────────────────────────
    (106, "photo", dict(key="br_counsel", kb="in")),
    (107, "photo", dict(key="p_office", kb="out")),
    (109, "photo", dict(key="p_friends", kb="in", tags=[(110, "“야 여기 가자.”", "left:160px;top:150px", "am"),
                                                        (111, "“나는 이거 별로야.”", "right:160px;top:290px", "am")],
                        nocap=[110, 111])),
    (113, "quotes", dict(bgkey="br_cafe_two", center=True, dim=.45, quotes=[(115, "저는 다 좋아요.", "y"),
                                                                (116, "괜찮아요.", "y"),
                                                                (117, "제가 혹시 부담드렸다면 죄송해요.", "y")],
                         nocap=[115, 116, 117])),
    (118, "typo", dict(parts=[(118, "왜 이렇게 될까?", "dim"), (119, "성격이 바뀐 게 아니다", ""),
                              (120, "좋은 평가를 받아야 한다는 압박", "am")])),
    (122, "quotes", dict(cut="cut_man_think_1", quotes=[(123, "말투", "am"), (124, "눈빛", "am"), (125, "자세", "am")],
                         layout="zig", nocap=[123, 124, 125])),
    (127, "flip", dict(rows=[(127, "상대 표정이 굳으면", 128, "방금 한 말을 다시 설명"),
                             (129, "상대가 웃지 않으면", 130, "바로 다른 이야기")])),
    (131, "typo", dict(parts=[(131, "나를 보여주기", "dim x"), (132, "좋아할 것 같은 사람 되기", "am")])),
    (133, "typo", dict(parts=[(134, "멘트에는 한계가 있다", "am")])),
    (137, "typo", dict(parts=[(137, "멘트를 몰라서가 아니다", "dim"),
                              (139, "진짜 문제|평소와 다른 태도로 바뀌는 것", "am")], nocap=[139, 140])),

    # ── CH2 하이에나와 사자 ──────────────────────────────────────────────────
    (141, "chapter", dict(num="02", title="하이에나와 사자", key="il_split")),
    (143, "video", dict(key="v_hyena", side="R", title=(143, "반응을 살피는 태도", "c-am"),
                        rows=[(143, "표정·말투를 계속 확인", "q"), (144, "조금만 달라져도 불안", "q"),
                              (146, "더 잘해주고, 더 맞춰주고", "q"), (149, "기준을 하나씩 포기", "no")])),
    (150, "cut", dict(key="cut_p_hyena", side="L", steps=[(151, "하이에나의 태도", "am")], nocap=[151])),
    (152, "center", dict(like_at=153, move_at=155)),
    (157, "video", dict(key="v_lion", side="R", title=(157, "반대로", "c-cy"),
                        rows=[(159, "좋아해도 기준 유지", "ok"), (161, "호감은 표현", "ok"),
                              (163, "만나고 싶으면 제안", "ok"), (165, "반응은 상대의 몫", "ok")])),
    (166, "cut", dict(key="cut_p_lion", side="L", steps=[(167, "사자의 태도", "cy")], nocap=[167])),
    (168, "rows", dict(items=[(169, "여자를 지배하라", "no", 171), (170, "무조건 내가 리드하라", "no", 171),
                                                 (171, "오히려 정반대", "ok")])),
    (172, "share", dict(mine=[(175, "좋으면 표현"), (176, "제안할 게 있으면 제안"), (177, "내 의견도 이야기")],
                        theirs_at=179)),
    (180, "cmp", dict(left=dict(title="하이에나", cls="am", img="p_hyena", at=180,
                                rows=[(182, "상대 반응을 보고"), (183, "내 행동을 계속 바꾼다")]),
                      right=dict(title="사자", cls="cy", img="p_lion", at=184,
                                 rows=[(185, "반응은 존중하되"), (186, "내 중심에서 행동한다")]))),
    (187, "typo", dict(parts=[(187, "겉으로는 둘 다 친절하다", "dim"), (189, "출발점이 다를 뿐", "am hl")], nocap=[189])),
    (190, "quotes", dict(quotes=[(191, "하이에나 : “이렇게 해야 나를 좋아해주겠지.”", "am"),
                                 (194, "사자 : “나는 이렇게 하고 싶다.”", "cy")], nocap=[191, 194])),
    (196, "words", dict(lead=(196, "그 차이가"), words=[(197, "말투", .02), (197, "표정", .77), (197, "행동", 1.33)])),

    # ── CH3 침묵 ─────────────────────────────────────────────────────────────
    (198, "chapter", dict(num="03", title="침묵", key="br_empty_chair")),
    (200, "timer", dict(label="2초", at=201, dur=2.0, sub="대화가 끊겼다", sub_at=201, key="cut_i_hourglass")),
    (202, "photo", dict(key="br_friends", kb="in")),
    (205, "timer", dict(label="2초", at=206, dur=2.8, sub="체감은 한참", sub_at=206)),
    (207, "quotes", dict(cut="cut_man_anx_4", quotes=[(208, "아 분위기 망했나?", "th"),
                                                     (209, "나 재미없다고 생각하는 거 아니야?", "th")],
                         layout="zig", nocap=[208, 209])),
    (210, "bubbles", dict(bgkey="br_silence_table", dim=.62,
                          msgs=[(211, "취미가 뭐예요?", "me"), (212, "여행 좋아하세요?", "me")], nocap=[211, 212])),
    (214, "roots", dict(top="질문", left="정말 궁금해서", right="침묵이 불안해서", top_at=214,
                        l_at=216, r_at=217)),
    (219, "typo", dict(parts=[(219, "둘은 완전히 다르다", "")], nocap=[219])),
    (220, "rows", dict(title="후자가 반복되면 → 면접", items=[(222, "상대: 질문에 대답", "n"),
                                                        (223, "나: 다음 질문 준비", "n")])),
    (224, "photo", dict(key="p_study", kb="out", side="R",
                        tags=[(226, "질문 리스트 50개", "right:160px;top:170px", ""),
                              (227, "대화 주제 100개", "right:160px;top:300px", ""),
                              (228, "카톡하는 방법", "right:160px;top:430px", "")])),
    (230, "typo", dict(parts=[(230, "실전에 나가면|머리가 하얘진다", ""),
                              (232, "소재가 아니라|‘침묵이 괜찮다’는 태도가 없어서", "am")], nocap=[231])),
    (234, "bubbles", dict(bgkey="p_couple_sil", dim=.62,
                          msgs=[(237, "그건 좀 의외네요.", "me"), (238, "저는 오히려 반대였어요.", "me")],
                          nocap=[237, 238])),
    (240, "typo", dict(parts=[(240, "상대에게서 소재를 뽑아내는 게 아니라", "dim x"),
                              (242, "내 생각과 경험도 가져오는 것", "cy hl")])),

    # ── CH4 카톡 4시간 ───────────────────────────────────────────────────────
    (244, "chapter", dict(num="04", title="답장 없는 4시간", key="br_phone")),
    (245, "timer", dict(label="4h", at=246, dur=2.6, sub="답장이 없다", sub_at=246, key="cut_i_phone")),
    (247, "quotes", dict(bgkey="p_bed", side="R", quotes=[(249, "왜 답장이 없지?", "th"),
                                                          (250, "내가 아까 말실수했나?", "th"),
                                                          (251, "갑자기 마음이 식은 건가?", "th")],
                         layout="zig", nocap=[249, 250, 251])),
    (252, "video", dict(key="v_phone", side="R", rows=[(252, "카톡창 들어갔다 나왔다", "q"), (253, "프로필 확인", "q"),
                                                  (254, "SNS 확인", "q")],
                        quotes=[(256, "오늘 많이 바쁜가 봐요 ㅎㅎ", "y", "나")], nocap=[256])),
    (257, "typo", dict(parts=[(258, "보내지 말라는 게 아니다", "dim"), (260, "먼저 확인할 것", "am")])),
    (261, "typo", dict(parts=[(261, "“왜 지금 이 메시지를 보내고 싶은가?”", "am")], nocap=[261])),
    (262, "roots", dict(top="똑같은 카톡", left="할 말이 있어서", right="불안을 못 견뎌서",
                        l_at=262, r_at=264, top_at=266)),
    (268, "eq", dict(rows=[(268, "차가운 하루", "망가진 내 하루"), (270, "늦은 답장", "내 가치 하락")])),
    (272, "photo", dict(key="p_decline", kb="in")),
    (274, "rows", dict(title="거절의 가능성을 감당하지 못하면", items=[(275, "상대 반응을 바꾸려고", "n"), (276, "더 웃겨주려고", "q"), (277, "더 잘해주려고", "q"),
                                                   (278, "더 좋은 사람처럼 보이려고", "q")])),
    (279, "quotes", dict(title=(280, "친절의 의미가 달라진다"), arrows=(1,),
                         quotes=[(282, "처음 : 이 사람에게 잘 해주고 싶다", "cy"),
                                 (285, "어느 순간 : 이 정도 하면 좋아해주겠지?", "am")],
                         nocap=[282, 285])),
    (287, "morph", dict(a_at=288, b_at=289)),
    (290, "quotes", dict(bgkey="p_phone", side="R", dim=.3, quotes=[(290, "이렇게 했는데 왜 답장이 이래?", "dk"),
                                                                    (291, "이만큼 맞췄는데 왜 안 좋아하지?", "dk")],
                         nocap=[290, 291])),
    (292, "typo", dict(parts=[(292, "대가 없는 친절이라 믿었지만", "dim"),
                              (294, "호감을 ‘보상’으로 기다리고 있었다", "am hl")])),
    (295, "photo", dict(key="br_listen", kb="in")),

    # ── CH5 관계의 투자 ──────────────────────────────────────────────────────
    (298, "chapter", dict(num="05", title="관계의 투자", key="il_seesaw")),
    (300, "invest", dict(pairs=[(303, "L", "질문"), (304, "R", "질문"), (305, "L", "내 이야기"),
                                (306, "R", "자기 이야기"), (307, "L", "호감"), (308, "R", "반응")])),
    (309, "invest", dict(lopsided=True, gap_label="상대가\n들어올 공간", gap_at=311,
                         pairs=[(312, "L", "전부 채움"), (313, "L", "대화 살리기"), (314, "L", "다시 연락"),
                                (315, "L", "다시 제안"), (317, "L", "해명까지")])),
    (318, "quotes", dict(cut="cut_man_think_2", quotes=[(319, "“저는 진짜 많이 노력했는데요.”", "y")], nocap=[319])),
    (320, "typo", dict(parts=[(321, "많이 노력했다", ""), (323, "너무 많이, 혼자", "am hl"),
                              (325, "혼자 유지하려 했던 관계", "dim")])),
    (326, "steps", dict(head=(326, "하이에나와 사자의 차이, 다시"), back_at=329, fwd_at=330)),
    (331, "graph_effort", dict(draw_at=333, peak_at=334)),
    (335, "video", dict(key="v_lion", side="R", title=(335, "사자의 태도", "c-cy"),
                        rows=[(336, "해야 할 표현은 한다", "ok"), (337, "먼저 연락", "ok"),
                              (338, "애프터 제안", "ok"), (339, "좋다고 말하기", "ok")])),
    (340, "typo", dict(parts=[(341, "표현한 다음에는", "dim"), (342, "반응을 볼 줄 안다", "cy")], nocap=[342])),
    (343, "share", dict(title_l="내 몫", title_r="상대의 몫", mine=[(343, "표현"), (343, "제안")],
                        theirs_at=344, divide_at=345, theirs_label="선택과 반응")),
    (346, "typo", dict(parts=[(347, "아무것도 안 하는 게 아니라", "dim"), (348, "할 만큼 하고", ""),
                              (349, "상대 몫까지는 하지 않는다", "cy hl")])),

    # ── CH6 세 가지 체크 ─────────────────────────────────────────────────────
    (351, "chapter", dict(num="06", title="세 가지 체크", key="br_mirror")),
    (353, "check", dict(num="1", title="내 의견을 실제로 말하는가",
                        quotes=[(355, "아무거나 괜찮아요.", "dk", 356), (357, "저는 고기 먹고 싶은데, 그쪽은 어때요?", "y")],
                        nocap=[355, 357])),
    (359, "typo", dict(parts=[(359, "상대 의견을 존중하면서", "dim"), (360, "내 의견도 같이 놓는다", "cy")], nocap=[360])),
    (361, "check", dict(num="2", title="들어올 공간을 남기는가", card="il_space",
                        rows=[(364, "연락했다면 → 답할 시간", "ok"), (366, "제안했다면 → 선택할 차례", "ok"),
                              (367, "모든 순간을 살리지 않기", "ok", .7)])),
    (368, "check", dict(num="3", title="거절을 피하려는 건 아닌가", rows=[(371, "이 질문을 자주 해보세요", "q")])),
    (372, "flip", dict(title="자주 물어보기",
                       rows=[(373, "정말 하고 싶어서?", 374, "싫어할까 봐?"),
                             (376, "정말 괜찮아서?", 377, "점수 따려고?")])),
    (378, "typo", dict(parts=[(378, "같은 행동이라도", "dim"), (379, "어디서 시작됐느냐가", ""),
                              (380, "느낌을 바꾼다", "am")])),

    # ── CH7 밀당은 답이 아니다 ───────────────────────────────────────────────
    (381, "quotes", dict(quotes=[(382, "“그럼 이제부터 내가 갑이 되어야겠다.”", "y")], nocap=[382])),
    (383, "rows", dict(items=[(384, "일부러 늦은 답장", "no"), (385, "관심 없는 척", "no"),
                                                (386, "먼저 연락 올 때까지 버티기", "no"), (387, "밀당", "no")])),
    (388, "typo", dict(parts=[(388, "중심이 생긴 게 아니다", ""), (389, "여전히 상대 반응에 매여 있다", "am")], nocap=[388])),
    (391, "timer", dict(label="2h", at=391, dur=3.0, sub="휴대폰만 보고 있다면", sub_at=392, key="cut_i_phone")),
    (393, "photo", dict(key="p_mask", kb="in")),
    (395, "quotes", dict(cut="cut_man_calm_1", quotes=[(396, "관심 있으면 → 표현", "cy"), (397, "좋으면 → 좋다고", "cy"),
                                                      (398, "만나고 싶으면 → 제안", "cy")])),
    (399, "eq", dict(rows=[(400, "상대의 거절", "자기 부정")])),
    (402, "typo", dict(parts=[(404, "선택받기 위해", "dim"), (405, "자기 기준을 버리기 때문", "am hl")], nocap=[405])),
    (406, "iceberg", dict(top="카톡 · 질문 · 애프터 타이밍", bottom="이성 앞에서 바뀌는 태도",
                          top_at=407, bot_at=410, title_top="얕은 기술", title_bot="진짜 문제")),
    (413, "cmp", dict(left=dict(title="평소의 나", cls="cy", img="p_friends", at=413,
                                rows=[(413, "여유 있다"), (415, "의견이 있다"), (417, "생활이 단단하다")]),
                      right=dict(title="그녀 앞의 나", cls="am", img="p_phone", at=414,
                                 rows=[(414, "조급해진다"), (416, "계속 맞춰준다"), (419, "카톡 하나에 흔들린다")]))),
    (420, "cycle", dict(nodes=[(423, "소개팅"), (424, "썸"), (425, "연애")], center="같은 태도",
                        center_at=428)),
    (430, "photo", dict(key="br_mirror", kb="in", dim=.72,
                        steps=[(433, "마음에 드는 여자 앞에서", "", .19), (433, "나는 어떻게 변하는가?", "am hl", 1.97)],
                        nocap=[433])),
    (435, "roots", dict(top="내가 한 말과 행동", left="보인다", right="태도는 안 보인다",
                        top_at=435, l_at=436, r_at=437)),
    (439, "flip", dict(rows=[(439, "질문이 많다", 440, "질문을 줄인다"),
                             (441, "카톡이 빠르다", 442, "일부러 늦게"),
                             (443, "너무 잘해준다", 444, "일부러 차갑게")])),
    (445, "photo", dict(key="p_mask", kb="out")),
    (450, "typo", dict(parts=[(450, "속은 흔들리는데", "dim"), (451, "겉만 여유 있는 척", "")], nocap=[451])),
    (452, "quotes", dict(cut="cut_man_anx_5", quotes=[(453, "말투", "am"), (454, "표정", "am"), (455, "목소리", "am")],
                         layout="zig", nocap=[453, 454])),

    # ── 마무리 ───────────────────────────────────────────────────────────────
    (456, "typo", dict(parts=[(456, "외운 멘트가 아니라", "dim"), (458, "상대를 대하는 태도", "am hl")], nocap=[458])),
    (459, "rows", dict(title="바뀌어야 할 태도", items=[(460, "마음에 들어도 중심을 잃지 않기", "ok"),
                                                   (462, "반응을 존중하며 기준을 표현하기", "ok"),
                                                   (464, "거절이 있어도 표현하기", "ok"),
                                                   (466, "내 몫과 상대 몫을 구분하기", "ok")])),
    (467, "typo", dict(parts=[(467, "태도가 바뀌면", "dim"), (468, "같은 말도 다르게 나온다", ""),
                              (471, "기술보다 태도가 먼저", "am")], nocap=[468])),
    (472, "reject", dict(link_at=472, cut_at=473)),
    (476, "typo", dict(parts=[(477, "좋은 멘트를 몰라서가 아니다", "dim x"),
                              (479, "나도 모르게 바뀌는 태도", "am hl")])),
    (480, "cta", dict(lines_at=[481, 486])),
    (488, "typo", dict(parts=[(490, "좋아하는 사람 앞에서", ""),
                              (491, "내 태도가 어떻게 바뀌는지 아는 것", "am hl")], nocap=[491])),
]
