# -*- coding: utf-8 -*-
"""Illustration prompts. refs: m = man sheet, w = woman sheet."""
STYLE = ("Flat 2D Korean webtoon-style cartoon illustration, clean bold dark outlines, simple cel shading, "
         "soft muted warm colors, expressive faces, uncluttered composition with the subject centered, "
         "plain soft light-gray background with subtle shapes, 16:9. Absolutely no text, letters, numbers or speech bubbles.")
MAN = "the same man as the reference sheet (short black hair, round black glasses, dark brown hoodie)"
WOMAN = "the same woman as the reference sheet (long straight brown hair, beige knit sweater)"
IMG = {
 "cafe_crush": ("mw", f"{MAN} sits across a small cafe table from {WOMAN}; he looks at her with a shy admiring smile, she sips coffee"),
 "m_nod": ("m", f"{MAN}, waist-up, nodding eagerly with a big agreeable smile, both hands raised in agreement"),
 "cafe_awkward": ("mw", f"{MAN} and {WOMAN} at a cafe table, both smiling stiffly, awkward mood, a small gap of silence between them, sweat drop on his temple"),
 "w_smile": ("w", f"{WOMAN}, waist-up, cheerfully talking, one hand gesturing, bright smile"),
 "w_spicy": ("w", f"{WOMAN}, waist-up, happily holding a bowl of very spicy red food with a chili pepper icon floating nearby, cheeks slightly red"),
 "m_eager": ("m", f"{MAN}, waist-up, leaning forward with an over-eager smile, pointing to himself, eager to agree"),
 "w_crowd": ("w", f"{WOMAN}, waist-up, slightly uncomfortable expression, gentle hand near ear, a faint crowd of tiny people silhouettes far behind her"),
 "m_proud": ("m", f"{MAN}, waist-up, confident proud smile, thumbs up, small sparkles around him"),
 "cafe_highfive": ("mw", f"{MAN} and {WOMAN} at a cafe table doing a small cheerful high five across the table"),
 "m_checklist": ("m", f"{MAN} holding a clipboard with three big green check marks, satisfied smile"),
 "clock_cafe": ("mw", f"{MAN} and {WOMAN} talking at a cafe table, a large wall clock above them with motion lines showing time passing, cups empty"),
 "cafe_blank": ("mw", f"{MAN} and {WOMAN} at a cafe table, each with an empty thought balloon above the head, puzzled faces"),
 "w_confused": ("w", f"{WOMAN}, waist-up, looking puzzled at the viewer, head tilted, one hand on chin, a question-mark shape made of dots floating"),
 "m_echo": ("m", f"{MAN}, waist-up, smiling blankly, surrounded by many small identical yellow empty rounded shapes echoing outward like ripples"),
 "teacher": ("", "A friendly Korean male lecturer in a white shirt and red necktie standing next to a green chalkboard with simple doodles, pointing forward with one finger, confident"),
 "teacher_x": ("", "The same friendly Korean male lecturer in a white shirt and red necktie, crossing both forearms in a big X gesture, calm smile, green chalkboard behind"),
 "heart_hands": ("mw", f"{MAN} and {WOMAN} sitting together, warmly listening to each other, a soft glowing heart floating between them"),
 "w_tteok": ("w", f"{WOMAN}, waist-up, holding chopsticks over a plate of red Korean tteokbokki rice cakes, delighted expression"),
 "m_tteok_fake": ("m", f"{MAN}, waist-up, holding tteokbokki with a forced fake smile, a small sweat drop, eyes slightly unsure"),
 "tteok_two": ("mw", f"{MAN} and {WOMAN} happily sharing a big plate of red tteokbokki at a snack bar, both genuinely enjoying"),
 "mirror_pose": ("mw", f"{WOMAN} and {MAN} sitting face to face, he exactly copies her pose like a mirror image (both resting chin on right hand), funny"),
 "m_groom": ("m", f"{MAN} fixing his hair in front of a small mirror, trying to look good, nervous determined face"),
 "m_nervous": ("m", f"{MAN}, waist-up, nervous smile, heavy sweat drops, hands clasped tightly"),
 "cafe_frozen": ("mw", f"{MAN} and {WOMAN} at a cafe table, the air between them frozen with blue ice crystals, both stiff and awkward"),
 "m_curious": ("m", f"{MAN}, waist-up, tilting his head with a playful curious smile, one eyebrow raised"),
 "w_eager": ("w", f"{WOMAN}, waist-up, leaning forward with eyes lit up, excited to explain, both hands open"),
 "w_laugh": ("w", f"{WOMAN}, waist-up, laughing warmly, eyes closed, hand near mouth"),
 "m_explain": ("m", f"{MAN}, waist-up, calmly explaining with both hands open, sincere relaxed face"),
 "m_confident": ("m", f"{MAN}, waist-up, relaxed confident posture, talking with a natural smile, hand on chest"),
 "w_happy": ("w", f"{WOMAN}, eating a bite of tteokbokki with blissful happy face, small hearts floating"),
 "tteok_to_people": ("mw", f"a plate of tteokbokki in the foreground turning into swirling soft light that flows up to {MAN} and {WOMAN} deeply talking behind it"),
 "w_thoughts": ("w", f"{WOMAN}, waist-up, thinking happily, surrounded by small floating icons: a smiling face, a stopwatch, a fork and spoon, a small cloud"),
 "cafe_lively": ("mw", f"{MAN} and {WOMAN} at a cafe table in a lively animated conversation, both gesturing and laughing, many small colorful sparkles"),
 "cafe_debate": ("mw", f"{MAN} and {WOMAN} in a friendly lively debate at a cafe table, she counts on fingers, he gestures, both smiling"),
 "thermo_cold": ("mw", f"{MAN} and {WOMAN} sitting politely at a table, a large cartoon thermometer between them showing a low pale blue level"),
 "cafe_still": ("mw", f"{MAN} and {WOMAN} sitting perfectly still at a table with identical polite smiles, completely motionless, dull calm mood"),
 "w_curious": ("w", f"{WOMAN}, waist-up, resting chin on hand, looking at the viewer with curious interested eyes"),
 "m_mountain": ("m", f"{MAN} climbing a steep small cartoon mountain with effort, a flag at the top"),
 "m_blush": ("m", f"{MAN}, waist-up, blushing hard, heart pounding shown with small hearts, stiff with pressure"),
 "w_pretty": ("w", f"{WOMAN}, waist-up, smiling beautifully, soft sparkles and flowers around her, charming"),
 "m_score": ("m", f"{MAN}, waist-up, with a big target board floating above his head, anxious calculating eyes"),
 "w_scorecard": ("mw", f"{WOMAN} holding up a blank score card, {MAN} across from her anxiously waiting for her judgment"),
 "m_zip": ("m", f"{MAN}, waist-up, a zipper across his mouth, holding back his opinion, awkward smile"),
 "w_blank_profile": ("w", f"{WOMAN} looking at a large blank profile card with an empty gray silhouette, puzzled"),
 "m_shrug": ("m", f"{MAN}, waist-up, shrugging with open palms and a passive smile"),
 "m_yes": ("m", f"{MAN}, waist-up, nodding and smiling with an index finger up, agreeing"),
 "m_fading": ("m", f"{MAN}, standing, his body becoming semi-transparent and fading away like mist, gentle sad tone"),
 "scale_balance": ("mw", f"a large balance scale perfectly level, {MAN} on one side and {WOMAN} on the other side, both calm and smiling"),
 "w_plan": ("w", f"{WOMAN}, waist-up, holding a neat travel planner notebook and a pen, a small map and suitcase icon beside her, organized smile"),
 "m_backpack": ("m", f"{MAN} with a backpack, carefree grin, standing at a scenic street, spontaneous traveler vibe"),
 "w_surprised": ("w", f"{WOMAN}, waist-up, pleasantly surprised, eyes wide, hand on cheek"),
 "m_relaxed": ("m", f"{MAN}, waist-up, relaxed easy smile, one hand behind his head, open and honest"),
 "w_seeing": ("w", f"{WOMAN}, waist-up, looking at the viewer with a warm understanding smile, eyes sparkling with interest"),
 "m_understand": ("m", f"{MAN}, waist-up, nodding with understanding, a small glowing light bulb above his head"),
 "paths_merge": ("", "Top-down view of two different paths, one straight and one winding, merging together into one wide road, green field, flat illustration"),
 "m_anxious": ("m", f"{MAN}, waist-up, anxious worried face, small dark storm cloud swirling above his head"),
 "m_shield": ("m", f"{MAN} hiding behind a big round shield, only his nervous smiling eyes visible"),
 "interview": ("mw", f"{MAN} across a table from {WOMAN}, reading questions from a notepad like a formal interview, she answers politely"),
 "m_sigh": ("m", f"{MAN}, waist-up, sighing, shoulders drooping, a small flat line icon near him"),
 "nod_pair": ("mw", f"{MAN} and {WOMAN} facing each other and nodding together warmly"),
 "m_think": ("m", f"{MAN}, waist-up, hand on chin, thoughtful expression, gently considering"),
 "m_idea": ("m", f"{MAN}, waist-up, index finger up explaining a reason, a light bulb shining above him"),
 "m_handover": ("m", f"{MAN}, waist-up, extending an open palm toward the side as if handing the turn to someone, kind smile"),
 "cafe_pingpong": ("mw", f"{MAN} and {WOMAN} at a table with a glowing ball arcing back and forth between them, playful"),
 "radio_sync": ("mw", f"{MAN} and {WOMAN} standing apart, colorful sound waves from each meeting and syncing in the middle"),
 "w_foodtalk": ("w", f"{WOMAN}, waist-up, happily talking about food, small icons of dishes around her"),
 "m_heavy": ("mw", f"{MAN} suddenly telling a very gloomy serious story under a dark rain cloud, {WOMAN} across the table startled"),
 "cafe_laugh": ("mw", f"{MAN} and {WOMAN} laughing together at a cafe table, relaxed and light"),
 "m_ring": ("mw", f"{MAN} awkwardly holding out a ring box too early, {WOMAN} shocked with a sweat drop"),
 "m_soccer": ("m", f"{MAN} excitedly talking while holding a soccer ball, eyes shining, arms waving"),
 "w_bored": ("w", f"{WOMAN}, waist-up, bored blank face, resting cheek on hand, half-closed eyes"),
 "radio_broken": ("mw", f"{MAN} and {WOMAN} with jagged broken static waves between them, lightning-shaped break in the middle"),
 "w_react": ("w", f"{WOMAN}, waist-up, leaning in with an interested reaction, eyes bright, attentive"),
 "two_paths": ("", "A road forking into two paths through a green field, top-down flat illustration, a small signpost at the fork"),
 "m_monologue": ("mw", f"{MAN} talking nonstop with an extremely long ribbon coming from his mouth, {WOMAN} across from him politely tired"),
 "m_sorry": ("m", f"{MAN}, waist-up, scratching the back of his head with a sheepish apologetic smile"),
 "m_crush": ("m", f"{MAN}, waist-up, heart-shaped eyes, dreamy smitten smile, hearts floating"),
 "finish_line": ("mw", f"{MAN} running alone far ahead toward a finish line ribbon, {WOMAN} still standing calmly at the start line in the distance"),
 "m_weight": ("m", f"{MAN} struggling under a huge heavy weight on his shoulders, strained face"),
 "puzzle_pair": ("mw", f"{MAN} and {WOMAN} each holding a large puzzle piece, trying to see if they fit together, curious smiles"),
 "m_interviewer": ("m", f"{MAN} holding a clipboard and pen like a strict interviewer, reading questions, serious face"),
 "m_datetalk": ("m", f"{MAN}, waist-up, walking outdoors, casually chatting with a natural friendly smile"),
 "date_walk": ("mw", f"{MAN} and {WOMAN} walking side by side along a tree-lined street, chatting naturally, relaxed"),
 "w_walk": ("w", f"{WOMAN}, waist-up, walking outdoors, smiling and talking naturally"),
 "clipboard": ("", "A clipboard with a long list of checkbox questions and question marks, a pen beside it, flat illustration"),
 "magnify": ("mw", f"{MAN} and {WOMAN} together looking through a big magnifying glass, discovering small glowing shapes, delighted"),
 "m_agree": ("m", f"{MAN}, waist-up, about to blurt out agreement, mouth open, raising his hand quickly, eager"),
 "m_mask": ("m", f"{MAN} holding a smiling mask in front of his face, his real eyes peeking out"),
 "m_frown": ("m", f"{MAN}, waist-up, blunt displeased face, arms crossed"),
 "m_calm": ("m", f"{MAN}, waist-up, calm and sincere, explaining gently with one open hand"),
 "ball_pass": ("mw", f"{MAN} gently tossing a soft glowing ball to {WOMAN} who catches it with a smile"),
 "m_podium": ("mw", f"{MAN} lecturing at a podium with a pointer, {WOMAN} sitting alone in the audience looking bored"),
 "m_ask": ("m", f"{MAN}, waist-up, asking a question with a warm open curious smile, palm up"),
 "cafe_warm": ("mw", f"{MAN} and {WOMAN} talking warmly at a cafe table, soft golden light, both engaged and comfortable"),
 "m_anchor": ("m", f"{MAN} standing firm and calm, feet grounded, a subtle anchor symbol glowing behind him"),
 "memory_fade": ("mw", "An old polaroid photo of a man and woman at a cafe, the image fading away into blank white, lying on a table"),
 "w_friendzone": ("w", f"{WOMAN}, waist-up, polite apologetic smile, one hand raised softly as if gently declining"),
 "lecture": ("", "An open laptop showing a video lecture play button, a notebook and a coffee cup beside it, warm desk lamp light"),
 "m_flashcards": ("m", f"{MAN} stressed, frantically memorizing a big stack of flashcards, pile of papers"),
}
