# index -> new spec (only scene-owning lines; + and = stay as they were)
NEW = {
0:"I cafe_crush|좋아하는 여자 앞에서", 1:"I m_nod|모든 걸 공감해주는 남자", 3:"I cafe_awkward|대화가 잘 안 통한다",
5:"K w:w_smile", 7:"K m:m_nod", 9:"K w:w_spicy", 11:"K m:m_eager", 13:"K w:w_crowd", 15:"K m:m_eager",
17:"I m_proud|잘하고 있다고 생각한다", 18:"I cafe_highfive|공통점도 찾았고", 19:"I m_checklist|공감도 해줬고",
21:"I m_checklist|실수도 없었다", 22:"I clock_cafe|한 시간 뒤", 24:"T 이상한 일",
25:"I cafe_blank|많이 얘기했는데 아는 게 없다", 27:"I w_confused|이 남자는 어떤 사람?", 29:"I m_echo|저도요",
31:"I teacher|하나 짚고 갈게요", 33:"I teacher_x|무시하라는 것도, 반대하라는 것도 아니다",
35:"I heart_hands|공감은 중요합니다", 38:"T 공감이 아닌 공감",
45:"K w:w_tteok", 47:"K m:m_tteok_fake", 49:"I tteok_two|둘 다 좋아한다면", 52:"I m_tteok_fake|사실은 별로 안 좋아한다",
54:"I mirror_pose|그냥 맞춰준 겁니다", 56:"I m_groom|잘 보이고 싶으니까", 58:"K mx:m_nervous",
59:"I cafe_frozen|분위기 이상해질까 봐", 60:"I mirror_pose|그래서 또 맞춰준다", 63:"K m:m_curious",
64:"I w_eager|할 말이 생긴다", 65:"K w:w_laugh", 67:"K m:m_explain", 68:"I m_confident|자기 생각을 말한다",
70:"K w:w_tteok", 72:"K m:m_curious", 75:"K w:w_happy", 78:"I tteok_to_people|떡볶이 이야기 → 사람 이야기",
80:"I w_thoughts|즐거움 · 효율 · 스트레스", 84:"I cafe_lively|이야기가 넓어진다",
96:"I cafe_debate|서로의 생각이 움직인다", 99:"I thermo_cold|생각이 전부 같으면",
101:"I cafe_still|움직일 이유가 적다", 102:"I cafe_debate|생각이 조금 다르면", 103:"I m_explain|왜 그런지 설명하게 된다",
104:"I w_curious|상대가 궁금해진다", 105:"I m_confident|내 생각도 말하게 된다", 107:"I w_thoughts|취향과 기준이 드러난다",
112:"I m_mountain|생각보다 어렵다", 114:"I m_blush|더 어려워진다", 115:"I w_pretty|마음에 들기 시작하면",
118:"I m_score|다른 목적이 들어온다", 120:"I w_scorecard|좋은 평가를 받고 싶어진다", 121:"I m_nervous|대화가 달라진다",
122:"I m_zip|반대 못 하고, 의견은 숨기고", 127:"I cafe_highfive|잘 맞는 것 같은 느낌",
131:"I w_blank_profile|판단할 재료가 없다", 133:"I clock_cafe|두 시간 뒤", 139:"K m:m_shrug", 142:"K m:m_yes",
144:"I cafe_still|편할 수는 있다", 145:"I m_fading|여러분은 어디에 있나요?",
151:"I scale_balance|내 생각도, 상대 생각도", 154:"K w:w_plan", 155:"I m_backpack|즉흥 여행을 좋아한다면",
156:"K m:m_backpack", 159:"K w:w_surprised", 161:"K m:m_relaxed", 163:"I w_seeing|벌써 사람이 보인다",
168:"K w:w_plan", 170:"K m:m_relaxed", 171:"I m_understand|더 이해하게 된다", 172:"I paths_merge|처음에는 달랐다",
180:"I m_echo|저도요", 184:"I m_anxious|불안", 188:"I m_shield|가장 안전한 선택",
193:"I thermo_cold|온도가 안 올라간다", 204:"I interview|정보 교환", 210:"I interview|대화는 이어지지만",
211:"I m_sigh|변화가 없다", 219:"I nod_pair|① 공감", 220:"K m:m_yes", 221:"I m_think|② 차이", 222:"K m:m_think",
223:"I m_idea|③ 이유", 224:"K m:m_idea", 225:"I m_handover|④ 다시 돌려주기", 226:"K m:m_handover",
227:"I cafe_pingpong|한쪽으로 흐르지 않는다", 228:"I cafe_pingpong|상대 생각 · 내 생각",
236:"I radio_sync|서로 다른 두 사람이", 241:"I w_foodtalk|음식 이야기 중인데", 242:"I m_heavy|갑자기 인생의 상처를?",
243:"I cafe_laugh|가벼운 농담 중인데", 244:"I m_ring|갑자기 결혼관을?", 245:"I radio_sync|오가는 에너지를 보고",
247:"I cafe_laugh|거기에 맞는 이야기", 249:"I m_soccer|내 얘기만 신나게?", 251:"I m_soccer|축구 얘기가 나왔는데",
253:"I w_bored|10분 동안 혼자", 256:"I w_bored|표정이 점점 사라진다", 258:"I radio_broken|주파수가 깨졌다",
260:"I w_react|항상 상대 반응이 들어간다", 276:"I two_paths|나에 대한 평가 / 상대에 대한 정보",
280:"I m_monologue|말이 길어진 것 같다면", 281:"I m_sorry|편하게 인정하면 된다", 282:"K m:m_sorry",
283:"I nod_pair|다시 상대에게 넘기기", 288:"I w_react|흐름을 보고 있는 것", 292:"I m_crush|마음에 드는 사람을 만났다",
294:"K m:m_crush", 298:"I finish_line|혼자 관계의 결승선까지", 300:"I m_weight|모든 말에 의미가 커진다",
306:"I w_curious|어떤 사람인지 궁금하다", 307:"I puzzle_pair|나랑 잘 맞는지 알아보고 싶다",
313:"K mx:m_interviewer", 314:"I m_interviewer|체크리스트처럼 묻기보다", 316:"K m:m_datetalk",
318:"I date_walk|자연스럽게", 320:"K w:w_walk", 322:"K m:m_datetalk", 324:"I date_walk|연애관이 자연스럽게 나온다",
327:"I clipboard|질문 목록으로 조사하는 게 아니라", 329:"I magnify|서로의 생각을 발견하기", 332:"K mx:m_agree",
341:"I m_mask|꾸밀 필요 없다", 343:"I w_seeing|그래야 상대가 나를 안다", 348:"I scale_balance|이해하면서도 다른 의견",
351:"K mx:m_frown", 353:"K m:m_calm", 354:"I m_calm|이유를 말해야 사람이 보인다", 357:"I ball_pass|다시 상대에게",
358:"I m_podium|대화는 발표가 아니다", 359:"K m:m_ask", 363:"I cafe_warm|관심을 가지면서도",
366:"I cafe_warm|자연스럽게 주고받기", 370:"I m_anchor|내 생각부터", 372:"K mx:m_agree", 374:"I m_shield|그냥 갈등을 피한 것",
376:"I memory_fade|기억에 남지 않는다", 383:"K w:w_friendzone", 385:"I lecture|설명란 무료 특강",
387:"I m_flashcards|정답을 외우는 게 아니다",
}
